### ISSUE TITLE
Plugin fails when space in path to root directory

### ISSUE THREAD

**Issue by Sherlouk** [MarcoEidinger/SwiftFormatPlugin#1]
Unclear to me currently why, though I'm trying to do a bit more digging but I can run the plugin fine and it says it's passed but it isn't actually formatting the files.

I've run `swiftformat .` from the root of the project and it works as expected and the files are reformatted.

I've tried adding the `--verbose` flag, but this is just crashing Xcode for me 😅 

Haven't yet tried via command line.

**Comment by Sherlouk** [comment]
Same experience through command line. Succeeds quickly but no actual changes.

If I add the `--verbose` flag here, it just stalls and doesn't finish.

**Comment by Sherlouk** [comment]
Worth noting, in case it's relevant, I do have a custom configuration file in the root of the directory (`.swiftformat`) but I'm testing rules which are both in the default ruleset as well as my custom one so should spot if it was working either way.

**Comment by MarcoEidinger** [comment]
In a simple example of mine the code gets formatted (see line 2 of `MyLibrary.swift` in the video below).

https://user-images.githubusercontent.com/4176826/182222904-d70c80f3-dfad-4d02-9216-4350e9a97657.mov

Is your Swift package open-source so that I can try?

**Comment by MarcoEidinger** [comment]
Or can you share the info in report navigator for the execution of the plugin?

Example

<img width="1127" alt="Screen Shot 2022-08-01 at 12 01 01 PM" src="https://user-images.githubusercontent.com/4176826/182225340-cb99633e-87ab-4c17-8aaf-a5314435ebdd.png">

**Comment by Sherlouk** [comment]
![image](https://user-images.githubusercontent.com/15193942/182228642-10e4dae9-8962-4f15-95d4-039a1bcef76a.png)

There's a whole lot of nothing being printed out. Definitely not like yours. I'm using v0.49.12.

**Comment by Sherlouk** [comment]
Code isn't open source, but if we're unable to figure it out I can try to reproduce in a smaller project. It's a Vapor project though - in case that adds some fun complexities?

Multiple targets, multiple products, including executables.
I've tried putting unformatted code in all targets to see if it was running in one but not others.

Tried with arguments and without.

**Comment by Sherlouk** [comment]
One thing of note, my file path has a space in it? I wonder if that's causing some problems?

**Comment by Sherlouk** [comment]
That was it. Having a space in the file path causing it to not fail but not to work either.

Removing the space from the path fixes the issue - though of course would be nice if that wasn't necessary!

**Comment by MarcoEidinger** [comment]
I'll fix in the next version (that adopts nicklockwood/SwiftFormat@0.49.13)

**Comment by Sherlouk** [comment]
No worries, thank you for your effort in creating the plugin Marco!

**Comment by MarcoEidinger** [comment]
Hi James,

would you mind trying out [this fix](https://github.com/MarcoEidinger/SwiftFormatPlugin/pull/2) ?

```
.package(url: "https://github.com/MarcoEidinger/SwiftFormatPlugin.git, branch: "fix")
```

Also, do you still get a crash when specifying `--verbose` as an argument? I didn't encounter that, so I wonder if that is caused by something else and I did not yet stumble upon.

**Comment by Sherlouk** [comment]
I can confirm that the fixed branch does address the issue with spaces in the path.

Unfortunately I'm still having problems with the verbose argument crashing Xcode - but a far less important issue for me! (though would be nice to know why...)

**Comment by MarcoEidinger** [comment]
Hi James,

I am unable to reproduce the issue. I'll try further, but in the meantime, I'll create a release for the fix as well as uptaking nicklockwood/SwiftFormat@0.49.13) 

Let me know if you can share a project in which the issue is reproducible.

Cheers,
Marco
